version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: multimodal-backend-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=sqlite:///app/dev_database.db
      - OPENAI_KEY=${OPENAI_KEY:-placeholder}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-placeholder}
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN:-placeholder}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY:-placeholder}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key}
      - CORS_ORIGINS=http://54.211.160.83:3000,http://54.211.160.83:8000,https://back-agent.com,https://api.back-agent.com
    volumes:
      - ../backend:/app
      - ../backend/uploads:/app/uploads
      - ../backend/logs:/app/logs
      - backend_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dev-network
    command: >
      sh -c "
        echo 'Starting development backend...' &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "

  mcp-perplexity:
    image: mcp/perplexity-ask:latest
    container_name: mcp-perplexity-dev
    restart: unless-stopped
    environment:
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY:-placeholder}
    networks:
      - dev-network
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    container_name: multimodal-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=https://api.back-agent.com
      - REACT_APP_WS_URL=wss://api.back-agent.com
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - VITE_REACT_APP_API_URL=https://api.back-agent.com
      - VITE_REACT_APP_WS_URL=wss://api.back-agent.com
    volumes:
      - ../frontend:/app
      - /app/node_modules
    networks:
      - dev-network
    depends_on:
      - backend

volumes:
  backend_data:
    driver: local

networks:
  dev-network:
    driver: bridge 