services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64 # Ensure AMD64 for M1 compatibility
    volumes:
      - ../..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
      # Lightweight data storage
      - data-storage:/workspace/data
      # AWS credentials from host (optional)
      - ~/.aws:/home/vscode/.aws:ro
    command: sleep infinity
    environment:
      - PYTHONPATH=/workspaces/background-multimodal-llm
      - DEVELOPMENT_MODE=cloud
      # Cloud service configurations
      - AWS_DEFAULT_REGION=us-east-1
      - HF_DATASETS_CACHE=/workspace/data/hf_cache
      - TRANSFORMERS_CACHE=/workspace/data/transformers_cache
      # API configurations
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_URL=http://localhost:8000
      # Development settings (loaded from .env file)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN:-}
    ports:
      - "3000:3000" # React frontend (Create React App)
      - "8000:8000" # FastAPI backend
    platform: linux/amd64

volumes:
  data-storage:
    driver: local
